name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and deploy Jekyll site
        uses: jekyll/actions-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
