name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # 你的默认分支，可能是 main 或 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and deploy Jekyll site
        uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
