name: Jekyll site CI

on:
  push:
    branches:
      - main  # 确保这里是你的源代码所在分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and publish to GitHub Pages
        uses: actions/jekyll-build-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
