name: Jekyll site CI

on:
  push:
    branches:
      - main  # 确保这里是你的源代码所在分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # 确保这里的 Ruby 版本与你的项目兼容

      - name: Install dependencies
        run: |
          bundle config set --local path vendor/bundle
          bundle install

      - name: Build and test
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
