name: Update README

on:
  push:
    branches:
      - main # 或者你使用的是 master 分支

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 确保完整地检出仓库

      - name: Generate README
        run: |
          echo "# Blog Posts" > README.md
          echo "" >> README.md
          declare -A fileDates

          for file in _post/*; do
            # 检查文件是否有git提交记录
            if git log -- $file > /dev/null 2>&1; then
              firstDate=$(git log --reverse --format="%ad" --date=short -- $file | head -1)
              lastDate=$(git log -1 --format="%ad" --date=short -- $file)
              if [[ -z "$firstDate" ]] || [[ -z "$lastDate" ]]; then
                echo "Warning: Empty date for file $file"
                continue
              fi
              name=$(basename $file)
              echo "Processing $file: $firstDate, Last modified: $lastDate"
              fileDates["$lastDate"]+="$firstDate - [$name]($file)\n"
            else
              echo "Skipping $file as it has no commit history."
            fi
          done

          for date in "${!fileDates[@]}"; do
            printf "${fileDates[$date]}" | sort -r >> README.md
          done
        shell: bash

      - name: Commit and Push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Update README.md with latest blog posts" || exit 0  # 防止无更改时出错
          git push
