name: Update README

on:
  push:
    branches:
      - main # 或者你使用的是 master 分支

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 确保完整地检出仓库

      - name: Generate README
        run: |
          echo "# Blog Posts" > README.md
          echo "" >> README.md

          # 创建一个临时文件来存储文件名、创建日期和最后修改日期
          temp_file=$(mktemp)

          for file in _posts/*; do
            # 检查文件是否有git提交记录
            if git log -- $file > /dev/null 2>&1; then
              # 获取文件的最后提交日期，精确到秒
              lastModifiedDate=$(git log -1 --format="%ad" --date=format:'%Y-%m-%d %H:%M' -- $file)
              # 获取文件的创建日期，精确到分钟
              createdDate=$(git log --reverse --format="%ad" --date=format:'%Y-%m-%d %H:%M' -- $file | head -1)
              # 获取原始文件名，用于显示
              pretty_name=$(basename "$file")
              # 获取URL编码后的文件名，用于链接
              url_name=$(basename "$file" | sed 's/ /%20/g')
              # 将最后修改日期（用于排序）、原始文件名、创建日期和最后修改日期写入临时文件
              echo "$lastModifiedDate - [$pretty_name](_posts/$url_name) - created: $createdDate - last modified: $lastModifiedDate" >> $temp_file
            else
              echo "Skipping $file as it has no commit history."
            fi
          done

          # 根据最后修改日期时间排序键逆序排序临时文件的内容，然后追加到README.md
          sort -r $temp_file >> README.md

          # 删除临时文件
          rm $temp_file
        shell: bash

      - name: Commit and Push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Update README.md with latest blog posts" || exit 0  # 防止无更改时出错
          git push
