name: Update README

on:
  push:
    branches:
      - main # 或者你使用的是 master 分支

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 确保完整地检出仓库

      - name: Generate README
        run: |
          echo "# Blog Posts" > README.md
          echo "" >> README.md

          # 创建一个临时文件来存储日期和文件名
          temp_file=$(mktemp)

          for file in _post/*; do
            # 检查文件是否有git提交记录
            if git log -- $file > /dev/null 2>&1; then
              # 获取文件的最后提交日期
              lastDate=$(git log -1 --format="%ad" --date=short -- $file)
              # 获取文件名
              name=$(basename $file)
              # 将日期和文件名写入临时文件
              echo "$lastDate - [$name]($file)" >> $temp_file
            else
              echo "Skipping $file as it has no commit history."
            fi
          done

          # 根据日期排序，最近的日期在前，然后将排序后的内容追加到README.md
          sort -r $temp_file >> README.md
          # 删除临时文件
          rm $temp_file
        shell: bash

      - name: Commit and Push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Update README.md with latest blog posts" || exit 0  # 防止无更改时出错
          git push
