name: Update README

on:
  push:
    branches:
      - main # 或者你使用的是 master 分支

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 确保完整地检出仓库

      - name: Generate README
        run: |
          echo "# Blog Posts" > README.md
          echo "" >> README.md
          declare -A fileDates

          for file in _post/*; do
            # 获取文件的首次提交日期
            firstDate=$(git log --reverse --format="%ad" --date=short -- $file | head -1)
            # 获取文件的最后提交日期
            lastDate=$(git log -1 --format="%ad" --date=short -- $file)
            # 获取文件名
            name=$(basename $file)
            # 将文件名和首次提交日期存储在关联数组中，以最后提交日期为键
            fileDates["$lastDate"]+="$firstDate - [$name]($file)\n"
          done

          # 对日期进行逆序排序并更新README
          for date in $(echo ${!fileDates[@]} | tr ' ' '\n' | sort -r); do
            echo -e "${fileDates[$date]}" >> README.md
          done

      - name: Commit and Push
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Update README.md with latest blog posts" || exit 0  # 防止无更改时出错
          git push
